package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"

	//	"transport-app/app/adapter/in/graphql/graph/mapper"

	"transport-app/app/adapter/in/graphql/graph/mapper"
	"transport-app/app/adapter/in/graphql/graph/model"
	"transport-app/app/domain"
)

// Orders is the resolver for the orders field.
// Orders es el resolver para el campo orders.
func (r *queryResolver) DeliveryUnitsReports(
	ctx context.Context,
	filter *model.DeliveryUnitsReportFilterInput,
	first *int,
	after *string,
	last *int,
	before *string,
) (*model.DeliveryUnitsReportConnection, error) {
	fmt.Println("executing Orders resolver with filter:", filter)
	requestedFields := CollectSelectedPaths(ctx)
	fmt.Println("Requested fields:", requestedFields)

	// Definir límites
	const maxLimit = 100 // límite máximo razonable para paginación
	limit := 1           // valor por defecto

	// Procesar first/last
	if first != nil {
		if *first > maxLimit {
			return nil, fmt.Errorf("requested limit %d exceeds maximum allowed limit of %d", *first, maxLimit)
		}
		limit = *first
	} else if last != nil {
		if *last > maxLimit {
			return nil, fmt.Errorf("requested limit %d exceeds maximum allowed limit of %d", *last, maxLimit)
		}
		limit = *last
	}

	// Procesar cursores si existen
	var afterID, beforeID *string

	if after != nil && *after != "" {
		decoded, err := base64.StdEncoding.DecodeString(*after)
		if err != nil {
			return nil, fmt.Errorf("invalid 'after' cursor: %v", err)
		}
		// Convertir el string decodificado a int64
		id, err := strconv.ParseInt(string(decoded), 10, 64)
		if err != nil {
			return nil, fmt.Errorf("invalid 'after' cursor format: %v", err)
		}
		s := strconv.FormatInt(id, 10)
		afterID = &s
	}

	if before != nil && *before != "" {
		decoded, err := base64.StdEncoding.DecodeString(*before)
		if err != nil {
			return nil, fmt.Errorf("invalid 'before' cursor: %v", err)
		}
		// Convertir el string decodificado a int64
		id, err := strconv.ParseInt(string(decoded), 10, 64)
		if err != nil {
			return nil, fmt.Errorf("invalid 'before' cursor format: %v", err)
		}
		s := strconv.FormatInt(id, 10)
		beforeID = &s
	}

	pagination := domain.Pagination{
		First:  first,
		After:  afterID,
		Last:   last,
		Before: beforeID,
	}

	if err := pagination.IsValid(); err != nil {
		return nil, err
	}

	requestedFieldsAsMap := ConvertSelectedPathsToMap(ctx)

	// Construir el filtro
	deliveryUnitsFilter := domain.DeliveryUnitsFilter{
		RequestedFields: requestedFieldsAsMap,
		Pagination:      pagination,
	}

	// Agregar filtros si existen
	if filter != nil {
		if filter.ReferenceIds != nil && len(filter.ReferenceIds) > 0 {
			// Convertir []*string a []string
			referenceIds := make([]string, len(filter.ReferenceIds))
			for i, ref := range filter.ReferenceIds {
				if ref != nil {
					referenceIds[i] = *ref
				}
			}
			deliveryUnitsFilter.ReferenceIds = referenceIds
		}
	}

	results, err := r.findDeliveryUnitsProjectionResult(ctx, deliveryUnitsFilter)
	if err != nil {
		return nil, err
	}

	// Verificar si hay más páginas antes de mapear
	hasNextPage := len(results) > limit
	if hasNextPage {
		results = results[:limit] // quitar el elemento extra antes de mapear
	}

	// Mapear solo los resultados que vamos a mostrar
	deliveryUnits := mapper.MapDeliveryUnits(ctx, results)

	// Construir edges
	edges := make([]*model.DeliveryUnitsReportEdge, len(deliveryUnits))
	for i, order := range deliveryUnits {
		// Codificar el ID numérico en base64
		cursor := base64.StdEncoding.EncodeToString([]byte(strconv.FormatInt(results[i].ID, 10)))
		edges[i] = &model.DeliveryUnitsReportEdge{
			Cursor: cursor,
			Node:   order,
		}
	}

	// Construir pageInfo con todos los campos requeridos
	var startCursor, endCursor string
	if len(edges) > 0 {
		startCursor = edges[0].Cursor
		endCursor = edges[len(edges)-1].Cursor
	}

	// Determinar hasPreviousPage y hasNextPage
	hasPreviousPage := before != nil
	if last != nil {
		// En paginación hacia atrás, hasNextPage es true si hay más resultados
		hasNextPage = len(results) > limit
		hasPreviousPage = len(results) > limit
	} else {
		// En paginación hacia adelante, hasNextPage es true si hay más resultados
		hasNextPage = len(results) > limit
	}

	pageInfo := &model.PageInfo{
		HasNextPage:     hasNextPage,
		HasPreviousPage: hasPreviousPage,
		StartCursor:     &startCursor,
		EndCursor:       endCursor,
	}

	return &model.DeliveryUnitsReportConnection{
		Edges:    edges,
		PageInfo: pageInfo,
	}, nil
}

func ptrString(v string) *string    { return &v }
func ptrInt(v int) *int             { return &v }
func ptrFloat64(v float64) *float64 { return &v }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) Todos(ctx context.Context) ([]*model.Order, error) {
	// Simulamos una respuesta con datos falsos (mock)
	return []*model.Order{
		{
			ID:          "1",
			ReferenceID: "REF123",
		},
		{
			ID:          "2",
			ReferenceID: "REF456",
		},
	}, nil
}
*/
