package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"transport-app/app/adapter/in/graphql/graph/model"
)

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(
	ctx context.Context,
	filter *model.NodeFilterInput,
	first *int, after *string,
	last *int, before *string) (*model.NodeConnection, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}
