tasks:
  - name: Setup Go 1.24.0
    init: |
      rm -rf /home/gitpod/go
      wget -q https://go.dev/dl/go1.24.0.linux-amd64.tar.gz
      tar -xzf go1.24.0.linux-amd64.tar.gz
      mv go /home/gitpod/go
      rm go1.24.0.linux-amd64.tar.gz
    command: |
      echo 'export PATH="/home/gitpod/go/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc
      go version

vscode:
  extensions:
    - golang.go