version: "2.4"
services:
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./osrm:/data
    command: "osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld /data/chile-latest.osrm"
    networks:
      - vroom-network
  vroom:
    image: vroomvrp/vroom-docker:v1.10.0
    container_name: vroom
    ports:
      - 3000:3000
    volumes:
      - ./vroom-conf/:/conf
    environment:
      - VROOM_ROUTER=osrm
    depends_on:
      - osrm
    networks:
      - vroom-network

networks:
  vroom-network:
    driver: bridge