version: "3.8"

services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend
    container_name: osrm
    command: osrm-routed --algorithm mld --max-table-size 2000 --max-viaroute-size 2000 --max-trip-size 2000 /data/chile-latest.osrm
    volumes:
      - ./osrm:/data
    ports:
      - "5000:5000"
    networks:
      - vroom-network

  vroom:
    image: ghcr.io/vroom-project/vroom-docker:v1.14.0
    container_name: vroom
    ports:
      - "3000:3000"
    volumes:
      - ./conf:/conf  # 🔁 Aquí montamos tu config.yml en /conf
    depends_on:
      - osrm
    networks:
      - vroom-network

networks:
  vroom-network:
    driver: bridge