services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend
    container_name: osrm
    command: osrm-routed --algorithm mld /data/chile-latest.osrm
    volumes:
      - ./osrm:/data
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - vroom-network

  vroom:
    image: ghcr.io/vroom-project/vroom-docker:v1.14.0
    container_name: vroom
    ports:
      - "3000:3000"
    environment:
      - VROOM_ROUTER=osrm
      - OSRM_HOST=172.24.0.2
      - OSRM_PORT=5000
    depends_on:
      - osrm
    networks:
      - vroom-network

networks:
  vroom-network:
    driver: bridge