services:
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    command: >
      sh -c "
        osrm-extract -p /opt/car.lua /data/chile-latest.osm.pbf && 
        osrm-partition /data/chile-latest.osm.pbf && 
        osrm-customize /data/chile-latest.osm.pbf && 
        osrm-routed --algorithm mld /data/chile-latest.osm.pbf
      "
    volumes:
      - ./osrm:/data
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - vroom-network
  vroom:
    image: ghcr.io/vroom-project/vroom-docker:v1.14.0
    container_name: vroom
    ports:
      - "3000:3000"
    environment:
      - VROOM_ROUTER=osrm
      - OSRM_HOST=osrm
    depends_on:
      - osrm
    restart: unless-stopped
    networks:
      - vroom-network

networks:
  vroom-network:
    driver: bridge