services:
  transport-app:
    image: ghcr.io/ignaciojeria/transport-app/transport-app-d0a6ffdd2b5a22c2c0423e7b340b3900:latest
    container_name: transport-app
    environment:
      - ENVIRONMENT=production
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - DB_STRATEGY=disabled
      - OPTIMIZATION_REQUESTED_SUBSCRIPTION=${OPTIMIZATION_REQUESTED_SUBSCRIPTION}
      - MASTER_NODE_URL=${MASTER_NODE_URL}
      - MASTER_NODE_API_KEY=${MASTER_NODE_API_KEY}
      - VROOM_PLANNER_URL=http://planner:3000
      - VROOM_OPTIMIZER_URL=http://optimizer:3000
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/key.json
    depends_on:
      - planner
      - optimizer
    networks:
      - vroom-network
