version: "3.8"

services:
  osrm:
    image: ghcr.io/ignaciojeria/transport-app/transport-app-osrm:latest
    container_name: osrm
    ports:
      - "5000:5000"
    networks:
      - vroom-network

  optimizer:
    image: ghcr.io/vroom-project/vroom-docker:v1.14.0
    container_name: optimizer
    ports:
      - "3000:3000"
    volumes:
      - ./conf/optimizer:/conf
    depends_on:
      - osrm
    networks:
      - vroom-network

  planner:
    image: ghcr.io/vroom-project/vroom-docker:v1.14.0
    container_name: planner
    ports:
      - "3001:3000"
    volumes:
      - ./conf/planner:/conf
    depends_on:
      - osrm
    networks:
      - vroom-network

  transport-app:
    image: ghcr.io/ignaciojeria/transport-app/transport-app-d0a6ffdd2b5a22c2c0423e7b340b3900:latest
    container_name: transport-app
    environment:
      - PORT=8081
      - ENVIRONMENT=local
      - GOOGLE_PROJECT_ID=einar-404623
      - DB_STRATEGY=disabled
      - OPTIMIZATION_REQUESTED_SUBSCRIPTION=transport-app-events-optimization-requested
      - MASTER_NODE_URL=http://host.docker.internal:8081
      - MASTER_NODE_API_KEY=key
      - VROOM_PLANNER_URL=http://planner:3000
      - VROOM_OPTIMIZER_URL=http://optimizer:3000
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
    volumes:
      - C:/_git/transport-app/key.json:/app/key.json
    networks:
      - vroom-network

networks:
  vroom-network:
    driver: bridge