cliArgs:
  geometry: true # retrieve geometry (-g)
  planmode: false # run vroom in plan mode (-c) if set to true
  threads: 16 # number of threads to use (-t)
  explore: 4 # exploration level to use (0..5) (-x)
  limit: '1mb' # max request size
  logdir: '/..' # the path for the logs relative to ./src
  logsize: '100M' # max log file size for rotation
  maxlocations: 1000 # max number of jobs/shipments locations
  maxvehicles: 200 # max number of vehicles
  override: true # allow cli options override (-c, -g, -l, -t, and -x)
  path: '/vroom-optimizer-app/' # VROOM path (if not in $PATH)
  port: 3000 # expressjs port
  router: 'osrm' # routing backend (osrm, libosrm, ors, or valhalla)
  timeout: 300000 # milli-seconds
  baseurl: '/' # base url for api

# Configuraciones adicionales para optimización
optimization:
  # Configuraciones de costos por tipo de vehículo
  vehicleCosts:
    default:
      fixed: 0 # Costo fijo por usar el vehículo
      per_hour: 3600 # Costo por hora de viaje (en centavos)
      per_km: 0 # Costo por kilómetro
    truck:
      fixed: 5000 # Costo fijo más alto para camiones
      per_hour: 4500 # Costo por hora más alto
      per_km: 50 # Costo por kilómetro
    van:
      fixed: 2000 # Costo fijo intermedio para furgonetas
      per_hour: 3000 # Costo por hora intermedio
      per_km: 30 # Costo por kilómetro
  
  # Configuraciones de prioridades
  priorities:
    high: 100 # Prioridad alta para entregas urgentes
    medium: 50 # Prioridad media (default)
    low: 10 # Prioridad baja para entregas no urgentes
  
  # Configuraciones de ventanas de tiempo
  timeWindows:
    default_service_time: 300 # 5 minutos de tiempo de servicio por defecto
    default_setup_time: 60 # 1 minuto de tiempo de preparación por defecto
    max_waiting_time: 1800 # 30 minutos máximo de tiempo de espera

routingServers:
  osrm:
    car:
      host: '0.0.0.0'
      port: '5000'
      timeout: 5000 # 5 segundos timeout
      retries: 3 # Número de reintentos
    bike:
      host: '0.0.0.0'
      port: '5001'
      timeout: 5000
      retries: 0
    foot:
      host: '0.0.0.0'
      port: '5002'
      timeout: 5000
      retries: 0
  ors:
    driving-car:
      host: '0.0.0.0/ors/v2'
      port: '8080'
      timeout: 10000 # 10 segundos para ORS
      retries: 2
    driving-hgv:
      host: '0.0.0.0/ors/v2'
      port: '8080'
      timeout: 10000
      retries: 2
    cycling-regular:
      host: '0.0.0.0/ors/v2'
      port: '8080'
      timeout: 10000
      retries: 2
    cycling-mountain:
      host: '0.0.0.0/ors/v2'
      port: '8080'
      timeout: 10000
      retries: 2
    cycling-road:
      host: '0.0.0.0/ors/v2'
      port: '8080'
      timeout: 10000
      retries: 2
    cycling-electric:
      host: '0.0.0.0/ors/v2'
      port: '8080'
      timeout: 10000
      retries: 2
    foot-walking:
      host: '0.0.0.0/ors/v2'
      port: '8080'
      timeout: 10000
      retries: 2
    foot-hiking:
      host: '0.0.0.0/ors/v2'
      port: '8080'
      timeout: 10000
      retries: 2
  valhalla:
    auto:
      host: '0.0.0.0'
      port: '8002'
      timeout: 8000 # 8 segundos para Valhalla
      retries: 2
    bicycle:
      host: '0.0.0.0'
      port: '8002'
      timeout: 8000
      retries: 2
    pedestrian:
      host: '0.0.0.0'
      port: '8002'
      timeout: 8000
      retries: 2
    motorcycle:
      host: '0.0.0.0'
      port: '8002'
      timeout: 8000
      retries: 2
    motor_scooter:
      host: '0.0.0.0'
      port: '8002'
      timeout: 8000
      retries: 2
    taxi:
      host: '0.0.0.0'
      port: '8002'
      timeout: 8000
      retries: 2
    hov:
      host: '0.0.0.0'
      port: '8002'
      timeout: 8000
      retries: 2
    truck:
      host: '0.0.0.0'
      port: '8002'
      timeout: 8000
      retries: 2
    bus:
      host: '0.0.0.0'
      port: '8002'
      timeout: 8000
      retries: 2