package strategy

const (
	ddTraceIDKey = "dd.trace_id"
	ddSpanIDKey  = "dd.span_id"
	ddServiceKey = "dd.service"
	ddEnvKey     = "dd.env"
	ddVersionKey = "dd.version"
)

const (
	OBSERVABILITY_STRATEGY      = "OBSERVABILITY_STRATEGY"
	OTEL_EXPORTER_OTLP_INSECURE = "OTEL_EXPORTER_OTLP_INSECURE"
	OTEL_EXPORTER_OTLP_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"
)

const (
	OPENOBSERVE_AUTHORIZATION = "OPENOBSERVE_AUTHORIZATION"
	OPENOBSERVE_ORGANIZATION  = "OPENOBSERVE_ORGANIZATION"
	OPENOBSERVE_STREAM_NAME   = "OPENOBSERVE_STREAM_NAME"
)
