// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type Order struct {
	ReferenceID string `json:"referenceId"`
}

type Query struct {
}
