// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddressInfo struct {
	AddressLine1 *string      `json:"addressLine1,omitempty"`
	AddressLine2 *string      `json:"addressLine2,omitempty"`
	Contact      *Contact     `json:"contact,omitempty"`
	District     *string      `json:"district,omitempty"`
	Coordinates  *Coordinates `json:"coordinates,omitempty"`
	Province     *string      `json:"province,omitempty"`
	State        *string      `json:"state,omitempty"`
	TimeZone     *string      `json:"timeZone,omitempty"`
	ZipCode      *string      `json:"zipCode,omitempty"`
}

type Carrier struct {
	NationalID *string `json:"nationalID,omitempty"`
	Name       *string `json:"name,omitempty"`
}

type CollectAvailabilityDate struct {
	Date      *string    `json:"date,omitempty"`
	TimeRange *TimeRange `json:"timeRange,omitempty"`
}

type Confidence struct {
	Level   *float64 `json:"level,omitempty"`
	Message *string  `json:"message,omitempty"`
	Reason  *string  `json:"reason,omitempty"`
}

type Contact struct {
	AdditionalContactMethods []*ContactMethod `json:"additionalContactMethods,omitempty"`
	Documents                []*Document      `json:"documents,omitempty"`
	Email                    *string          `json:"email,omitempty"`
	FullName                 *string          `json:"fullName,omitempty"`
	NationalID               *string          `json:"nationalID,omitempty"`
	Phone                    *string          `json:"phone,omitempty"`
}

type ContactMethod struct {
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

type Coordinates struct {
	Latitude   *float64    `json:"latitude,omitempty"`
	Longitude  *float64    `json:"longitude,omitempty"`
	Source     *string     `json:"source,omitempty"`
	Confidence *Confidence `json:"confidence,omitempty"`
}

type DateRange struct {
	StartDate *string `json:"startDate,omitempty"`
	EndDate   *string `json:"endDate,omitempty"`
}

type Delivery struct {
	Recipient      *DeliveryRecipient `json:"recipient,omitempty"`
	HandledAt      *string            `json:"handledAt,omitempty"`
	Failure        *DeliveryFailure   `json:"failure,omitempty"`
	Location       *DeliveryLocation  `json:"location,omitempty"`
	EvidencePhotos []*EvidencePhoto   `json:"evidencePhotos,omitempty"`
}

type DeliveryFailure struct {
	Detail      *string `json:"detail,omitempty"`
	Reason      *string `json:"reason,omitempty"`
	ReferenceID *string `json:"referenceID,omitempty"`
}

type DeliveryLocation struct {
	Latitude  *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
}

type DeliveryRecipient struct {
	FullName   *string `json:"fullName,omitempty"`
	NationalID *string `json:"nationalID,omitempty"`
}

type DeliveryUnit struct {
	Dimensions *Dimension `json:"dimensions,omitempty"`
	Insurance  *Insurance `json:"insurance,omitempty"`
	Items      []*Item    `json:"items,omitempty"`
	Labels     []*Label   `json:"labels,omitempty"`
	Lpn        *string    `json:"lpn,omitempty"`
	Weight     *Weight    `json:"weight,omitempty"`
}

type DeliveryUnitsReport struct {
	ID                      string                   `json:"id"`
	Commerce                *string                  `json:"commerce,omitempty"`
	Consumer                *string                  `json:"consumer,omitempty"`
	Channel                 *string                  `json:"channel,omitempty"`
	Status                  *string                  `json:"status,omitempty"`
	DeliveryInstructions    *string                  `json:"deliveryInstructions,omitempty"`
	ReferenceID             string                   `json:"referenceID"`
	GroupBy                 *GroupBy                 `json:"groupBy,omitempty"`
	CollectAvailabilityDate *CollectAvailabilityDate `json:"collectAvailabilityDate,omitempty"`
	Destination             *Location                `json:"destination,omitempty"`
	Origin                  *Location                `json:"origin,omitempty"`
	OrderType               *OrderType               `json:"orderType,omitempty"`
	DeliveryUnit            *DeliveryUnit            `json:"deliveryUnit,omitempty"`
	PromisedDate            *PromisedDate            `json:"promisedDate,omitempty"`
	References              []*Reference             `json:"references,omitempty"`
	ExtraFields             []*KeyValuePair          `json:"extraFields"`
	Carrier                 *Carrier                 `json:"carrier,omitempty"`
	Vehicle                 *Vehicle                 `json:"vehicle,omitempty"`
	Driver                  *Driver                  `json:"driver,omitempty"`
	Route                   *Route                   `json:"route,omitempty"`
	Delivery                *Delivery                `json:"delivery,omitempty"`
}

type DeliveryUnitsReportConnection struct {
	Edges    []*DeliveryUnitsReportEdge `json:"edges"`
	PageInfo *PageInfo                  `json:"pageInfo"`
}

type DeliveryUnitsReportEdge struct {
	Cursor string               `json:"cursor"`
	Node   *DeliveryUnitsReport `json:"node"`
}

type DeliveryUnitsReportFilterInput struct {
	ReferenceIds         []*string               `json:"referenceIds,omitempty"`
	Lpns                 []*string               `json:"lpns,omitempty"`
	OriginNodeReferences []*string               `json:"originNodeReferences,omitempty"`
	Commerces            []*string               `json:"commerces,omitempty"`
	Consumers            []*string               `json:"consumers,omitempty"`
	References           []*ReferenceFilterInput `json:"references,omitempty"`
	Labels               []*LabelFilterInput     `json:"labels,omitempty"`
}

type Dimension struct {
	Length *int    `json:"length,omitempty"`
	Height *int    `json:"height,omitempty"`
	Width  *int    `json:"width,omitempty"`
	Unit   *string `json:"unit,omitempty"`
}

type Document struct {
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

type Driver struct {
	NationalID *string `json:"nationalID,omitempty"`
	Name       *string `json:"name,omitempty"`
	Email      *string `json:"email,omitempty"`
}

type EvidencePhoto struct {
	TakenAt *string `json:"takenAt,omitempty"`
	Type    *string `json:"type,omitempty"`
	URL     *string `json:"url,omitempty"`
}

type GroupBy struct {
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

type Insurance struct {
	Currency  *string `json:"currency,omitempty"`
	UnitValue *int    `json:"unitValue,omitempty"`
}

type Item struct {
	Sku         *string    `json:"sku,omitempty"`
	Description *string    `json:"description,omitempty"`
	Dimensions  *Dimension `json:"dimensions,omitempty"`
	Insurance   *Insurance `json:"insurance,omitempty"`
	Skills      []*Skill   `json:"skills,omitempty"`
	Quantity    *Quantity  `json:"quantity,omitempty"`
	Weight      *Weight    `json:"weight,omitempty"`
}

type KeyValuePair struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Label struct {
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

type LabelFilterInput struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

type Location struct {
	AddressInfo *AddressInfo `json:"addressInfo,omitempty"`
	NodeInfo    *NodeInfo    `json:"nodeInfo,omitempty"`
}

type NodeInfo struct {
	ReferenceID *string `json:"referenceId,omitempty"`
	Name        *string `json:"name,omitempty"`
}

type OrderType struct {
	Type        *string `json:"type,omitempty"`
	Description *string `json:"description,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       string  `json:"endCursor"`
}

type PromisedDate struct {
	DateRange       *DateRange `json:"dateRange,omitempty"`
	ServiceCategory *string    `json:"serviceCategory,omitempty"`
	TimeRange       *TimeRange `json:"timeRange,omitempty"`
}

type Quantity struct {
	QuantityNumber *int    `json:"quantityNumber,omitempty"`
	QuantityUnit   *string `json:"quantityUnit,omitempty"`
}

type Query struct {
}

type Reference struct {
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

type ReferenceFilterInput struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}

type Route struct {
	RouteID       *string `json:"routeID,omitempty"`
	LpnContainer  *string `json:"lpnContainer,omitempty"`
	RoutePosition *int    `json:"routePosition,omitempty"`
}

type Skill struct {
	Type        *string `json:"type,omitempty"`
	Value       *string `json:"value,omitempty"`
	Description *string `json:"description,omitempty"`
}

type TimeRange struct {
	StartTime *string `json:"startTime,omitempty"`
	EndTime   *string `json:"endTime,omitempty"`
}

type Vehicle struct {
	Plate *string `json:"plate,omitempty"`
}

type Weight struct {
	Unit  *string `json:"unit,omitempty"`
	Value *int    `json:"value,omitempty"`
}
