// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddressInfo struct {
	AddressLine1 *string  `json:"addressLine1,omitempty"`
	AddressLine2 *string  `json:"addressLine2,omitempty"`
	Contact      *Contact `json:"contact,omitempty"`
	District     *string  `json:"district,omitempty"`
	Latitude     *float64 `json:"latitude,omitempty"`
	Longitude    *float64 `json:"longitude,omitempty"`
	Province     *string  `json:"province,omitempty"`
	State        *string  `json:"state,omitempty"`
	TimeZone     *string  `json:"timeZone,omitempty"`
	ZipCode      *string  `json:"zipCode,omitempty"`
}

type CollectAvailabilityDate struct {
	Date      *string    `json:"date,omitempty"`
	TimeRange *TimeRange `json:"timeRange,omitempty"`
}

type Contact struct {
	AdditionalContactMethods []*ContactMethod `json:"additionalContactMethods,omitempty"`
	Documents                []*Document      `json:"documents,omitempty"`
	Email                    *string          `json:"email,omitempty"`
	FullName                 *string          `json:"fullName,omitempty"`
	NationalID               *string          `json:"nationalID,omitempty"`
	Phone                    *string          `json:"phone,omitempty"`
}

type ContactMethod struct {
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

type DateRange struct {
	StartDate *string `json:"startDate,omitempty"`
	EndDate   *string `json:"endDate,omitempty"`
}

type Dimension struct {
	Length *int    `json:"length,omitempty"`
	Height *int    `json:"height,omitempty"`
	Width  *int    `json:"width,omitempty"`
	Unit   *string `json:"unit,omitempty"`
}

type Document struct {
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

type ExtraFields struct {
	DestinationPoliticalAreaID *string `json:"destinationPoliticalAreaId,omitempty"`
}

type Insurance struct {
	Currency  *string `json:"currency,omitempty"`
	UnitValue *int    `json:"unitValue,omitempty"`
}

type Item struct {
	Sku         *string    `json:"sku,omitempty"`
	Description *string    `json:"description,omitempty"`
	Dimensions  *Dimension `json:"dimensions,omitempty"`
	Insurance   *Insurance `json:"insurance,omitempty"`
	Skills      []*Skill   `json:"skills,omitempty"`
	Quantity    *Quantity  `json:"quantity,omitempty"`
	Weight      *Weight    `json:"weight,omitempty"`
}

type Label struct {
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

type Location struct {
	AddressInfo          *AddressInfo `json:"addressInfo,omitempty"`
	DeliveryInstructions *string      `json:"deliveryInstructions,omitempty"`
	NodeInfo             *NodeInfo    `json:"nodeInfo,omitempty"`
}

type Node struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type NodeInfo struct {
	ReferenceID *string `json:"referenceId,omitempty"`
	Name        *string `json:"name,omitempty"`
}

type Order struct {
	ReferenceID             string                   `json:"referenceID"`
	CollectAvailabilityDate *CollectAvailabilityDate `json:"collectAvailabilityDate,omitempty"`
	Destination             *Location                `json:"destination,omitempty"`
	Origin                  *Location                `json:"origin,omitempty"`
	OrderType               *OrderType               `json:"orderType,omitempty"`
	Packages                []*Package               `json:"packages,omitempty"`
	PromisedDate            *PromisedDate            `json:"promisedDate,omitempty"`
	References              []*Reference             `json:"references,omitempty"`
	ExtraFields             *ExtraFields             `json:"extraFields,omitempty"`
}

type OrderConnection struct {
	Edges      []*OrderEdge `json:"edges"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount *int         `json:"totalCount,omitempty"`
}

type OrderEdge struct {
	Cursor string `json:"cursor"`
	Node   *Order `json:"node"`
}

type OrderFilterInput struct {
	ReferenceIds         []string `json:"referenceIds,omitempty"`
	ReferenceType        *string  `json:"referenceType,omitempty"`
	ReferenceValue       *string  `json:"referenceValue,omitempty"`
	Lpns                 []string `json:"lpns,omitempty"`
	OriginNodeReferences []string `json:"originNodeReferences,omitempty"`
	GroupBy              []string `json:"groupBy,omitempty"`
	LabelType            *string  `json:"labelType,omitempty"`
	LabelValue           *string  `json:"labelValue,omitempty"`
	Commerces            []string `json:"commerces,omitempty"`
	Consumers            []string `json:"consumers,omitempty"`
}

type OrderType struct {
	Type        *string `json:"type,omitempty"`
	Description *string `json:"description,omitempty"`
}

type Package struct {
	Dimensions *Dimension `json:"dimensions,omitempty"`
	Insurance  *Insurance `json:"insurance,omitempty"`
	Items      []*Item    `json:"items,omitempty"`
	Labels     []*Label   `json:"labels,omitempty"`
	Lpn        *string    `json:"lpn,omitempty"`
	Weight     *Weight    `json:"weight,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       string  `json:"endCursor"`
}

type PromisedDate struct {
	DateRange       *DateRange `json:"dateRange,omitempty"`
	ServiceCategory *string    `json:"serviceCategory,omitempty"`
	TimeRange       *TimeRange `json:"timeRange,omitempty"`
}

type Quantity struct {
	QuantityNumber *int    `json:"quantityNumber,omitempty"`
	QuantityUnit   *string `json:"quantityUnit,omitempty"`
}

type Query struct {
}

type Reference struct {
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

type Skill struct {
	Type        *string `json:"type,omitempty"`
	Value       *string `json:"value,omitempty"`
	Description *string `json:"description,omitempty"`
}

type TimeRange struct {
	StartTime *string `json:"startTime,omitempty"`
	EndTime   *string `json:"endTime,omitempty"`
}

type Weight struct {
	Unit  *string `json:"unit,omitempty"`
	Value *int    `json:"value,omitempty"`
}
