services:
  transport-app:
    image: ghcr.io/ignaciojeria/transport-app/transport-app-allinone:latest
    container_name: transport-app-allinone
    environment:
      - ENVIRONMENT=prod
      - DB_STRATEGY=disabled
      - OPTIMIZATION_REQUESTED_SUBSCRIPTION=transport-app-events-optimization-requested
      - MASTER_NODE_URL=https://einar-main-f0820bc.d2.zuplo.dev
      - MASTER_NODE_WEBHOOKS_URL=https://einar-main-f0820bc.d2.zuplo.dev/webhooks/
      - VROOM_PLANNER_URL=http://localhost:3001
      - VROOM_OPTIMIZER_URL=http://localhost:3000
      - NATS_CONNECTION_URL=connect.ngs.global
      - NATS_CONNECTION_CREDS_FILECONTENT=${NATS_CONNECTION_CREDS_FILECONTENT}
      - CACHE_STRATEGY=${CACHE_STRATEGY}
      - CACHE_URL=${CACHE_URL}