name: Build All-in-One with Dagger

# Solo ejecución manual
on:
  workflow_dispatch:

jobs:
  build-allinone:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Dagger All-in-One build and publish
      run: go run ./main.go
      working-directory: ./dagger/allinone 