name: Build Optimizator Node with Dagger

on:
  push:
    branches:
      - main

jobs:
  check-version-change:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.filter.outputs.version }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4

      -
        name: Check if .version file changed
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            version:
              - '.version'

  build-optimizator-node:
    runs-on: ubuntu-latest
    needs: [check-version-change, build-and-push]
    if: needs.check-version-change.outputs.version_changed == 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Dagger Optimizator Node build, validate and publish
      run: go run ./build_optimizator_node.go
      working-directory: ./dagger/optimizator
      env:
        NATS_CONNECTION_CREDS_FILECONTENT: ${{ secrets.NATS_CONNECTION_CREDS_FILECONTENT }}
        IMAGE_TAG: ${{ github.sha }}