name: 'Build OSRM Image'

on:
  workflow_dispatch:

jobs:
  build-osrm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push OSRM image
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="${REPO_NAME}-osrm"
          IMAGE_TAG="ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/${IMAGE_NAME}:latest"
          
          echo "Building OSRM image: $IMAGE_TAG"
          
          docker build \
            --file Dockerfile.osrm \
            --tag "$IMAGE_TAG" \
            --platform linux/amd64 \
            .
          
          echo "Pushing OSRM image..."
          docker push "$IMAGE_TAG"
          
          echo "OSRM image built and pushed successfully: $IMAGE_TAG" 