name: Build Vroom Planner & Optimizer with Dagger

# Solo ejecución manual
on:
  workflow_dispatch:

jobs:
  build-optimizator-node:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Dagger Optimizator Node build, validate and publish
      run: go run ./build_vroom.go
      working-directory: ./dagger/vroom
      env:
        IMAGE_TAG: ${{ github.sha }}